// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmGhjhLzCv9Q8dv-OuZioeQ6izXAg8kzA',
    appId: '1:970625054280:web:4d6ee714d069d2193c4a7d',
    messagingSenderId: '970625054280',
    projectId: 'paais-ccfe8',
    authDomain: 'paais-ccfe8.firebaseapp.com',
    storageBucket: 'paais-ccfe8.firebasestorage.app',
    measurementId: 'G-6156FLDQBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76ihuat-ymPyZlFpGaXi0hikn4X5FuiU',
    appId: '1:970625054280:android:abd444c3bce574de3c4a7d',
    messagingSenderId: '970625054280',
    projectId: 'paais-ccfe8',
    storageBucket: 'paais-ccfe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBARyeAMPZssktlEKgiYbI0v93OGiLiMjw',
    appId: '1:970625054280:ios:bc52cd9e5ee431263c4a7d',
    messagingSenderId: '970625054280',
    projectId: 'paais-ccfe8',
    storageBucket: 'paais-ccfe8.firebasestorage.app',
    iosBundleId: 'com.example.panAfricanAiSummit',
  );
}
